
trigger:
- main

pool:
  Sare_Bahano
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'Sutradhar-Serviceconnection'
    environmentAzureRmOverrideSubscriptionID: '6e2d972f-0c29-493d-bc26-2eaa32b9e4b9'